version: '3.8'
services:
  aspapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - .:/app
      - ./Logs:/app/Logs
