version: '3.8'
services:
  nextjs:
    container_name: nextjs-app
    build: .
    ports:
      - "3250:3000" # Map port 3250 on the host to 3000 in the container
    environment:
      - NODE_ENV=production
