name: Docker Compose Up

on:
  push:
    branches:
      - main  # Set this to the branches where you want the action to run
  pull_request:
    branches:
      - main  # Set this to the branches where you want the action to run

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest  # Choose an appropriate runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Docker Compose Up
      run: |
        docker-compose up --build -d

    - name: Prune Docker Images
      run: |
        docker image prune -f

